eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
management:
   endpoint:
     health:
       enabled: true
     info:
       enabled: true
     loggers:
       enabled: true
     metrics:
       enabled: true
   endpoints:
      web:
        exposure:
            include:
             - health
             - configprops
             - loggers
             - metrics
             - info
             - httptrace
             - env