


management:
   endpoint:
     health:
       enabled: true
     info:
       enabled: true
     loggers:
       enabled: true
     metrics:
       enabled: true
   endpoints:
      web:
        exposure:
            include:
             - health
             - configprops
             - loggers
             - metrics
             - info
             - httptrace
             - env